title: Alexander Haskey
#theme: jekyll-theme-minimal
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
#google_analytics: [Your Google Analytics tracking ID]

